AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an IAM role for selected permissions (__VERSION__)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: ""
      Parameters:
      - Permissions
    - Label:
        default: Advanced Configuration (optional)
      Parameters:
      - STSRoles
      - TrustedAccount
    ParameterLabels:
      Permissions:
        default: IAM role
      STSRoles:
        default: STS roles
      TrustedAccount:
        default: Trusted Account ID
Parameters:
  TrustedAccount:
    Description: A 12 digits number that represents the ID of a trusted account. IAM users in this account will be able assume the IAM role and receive the permissions attached to it.
    Type: String
    Default: ""
    AllowedPattern: ^([0-9]{12})|$
  STSRoles:
    Description: The IAM role will be able to assume these STS Roles (comma separated list of ARNs, without spaces)
    Type: String
    Default: ""
  Permissions:
    Type: String
    Default: Create with read permissions
    AllowedValues:
    - Create with read permissions
    - Create with read-write permissions
    - Create with assume role permissions (specify an STS role ARN)
Conditions:
  ProvidedSTSRoles: !Not [!Equals [!Ref STSRoles, ""]]
  ProvidedTrustedAccount: !Not [!Equals ["", !Ref TrustedAccount]]
  NotProvidedTrustedAccount: !Equals ["", !Ref TrustedAccount]
  AllowReadPermissions: !Or
  - !Equals
    - Ref: Permissions
    - Create with read permissions
  - !Equals
    - Ref: Permissions
    - Create with read-write permissions
  AllowCreatePermissions: !Equals
  - Ref: Permissions
  - Create with read-write permissions
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - !If
          - ProvidedTrustedAccount
          - Effect: Allow
            Principal:
              AWS:
              - !Ref TrustedAccount
            Action:
            - sts:AssumeRole
          - Ref: AWS::NoValue
        - !If
          - NotProvidedTrustedAccount
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
            - sts:AssumeRole
          - Ref: AWS::NoValue
      Path: /
      Policies:
      - PolicyName: Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - !If
            - ProvidedSTSRoles
            - Effect: Allow
              Action:
              - sts:AssumeRole
              Resource: !Split [",", !Ref STSRoles]
            - Ref: AWS::NoValue
          - !If
            - AllowReadPermissions
            - Effect: Allow
              Action:
              - ec2:DescribeInstances
              - ec2:DescribeNetworkInterfaces
              - ec2:DescribeSubnets
              - ec2:DescribeVpcs
              - ec2:DescribeVpnGateways
              - ec2:DescribeVpnConnections
              - ec2:DescribeSecurityGroups
              - elasticloadbalancing:DescribeLoadBalancers
              - elasticloadbalancing:DescribeTags
              - elasticloadbalancing:DescribeListeners
              - elasticloadbalancing:DescribeTargetGroups
              - elasticloadbalancing:DescribeRules
              - elasticloadbalancing:DescribeTargetHealth
              - autoscaling:DescribeAutoScalingGroups
              Resource: '*'
            - Ref: AWS::NoValue
          - !If
            - AllowCreatePermissions
            - Effect: Allow
              Action:
              - ec2:DescribeCustomerGateways
              - ec2:CreateCustomerGateway
              - ec2:DeleteCustomerGateway
              - ec2:DescribeRouteTables
              - ec2:EnableVgwRoutePropagation
              - ec2:DisableVgwRoutePropagation
              - ec2:DescribeVpnGateways
              - ec2:CreateVpnGateway
              - ec2:AttachVpnGateway
              - ec2:DetachVpnGateway
              - ec2:DeleteVpnGateway
              - ec2:DescribeVpnConnections
              - ec2:CreateVpnConnection
              - ec2:DeleteVpnConnection
              - ec2:DescribeTransitGateways
              - ec2:DescribeTransitGatewayRouteTables
              - ec2:DescribeTransitGatewayAttachments
              - ec2:AssociateTransitGatewayRouteTable
              - ec2:DisassociateTransitGatewayRouteTable
              - ec2:EnableTransitGatewayRouteTablePropagation
              - ec2:DisableTransitGatewayRouteTablePropagation
              - ec2:GetTransitGatewayAttachmentPropagations
              Resource: '*'
            - Ref: AWS::NoValue
          - !If
            - AllowCreatePermissions
            - Effect: Allow
              Action:
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackResources
              Resource: '*'
            - Ref: AWS::NoValue
          - !If
            - AllowCreatePermissions
            - Effect: Allow
              Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              Resource: arn:aws:cloudformation:*:*:stack/vpn-by-tag--*/*
            - Ref: AWS::NoValue
Outputs:
    IAMRole:
        Description: The IAM role
        Value: !Ref IAMRole
    ARNRole:
        Description: The IAM role ARN
        Value: !GetAtt IAMRole.Arn